### ISSUE TITLE
ac_mode not working for me

### ISSUE THREAD

**Issue by pcrednet** [swingerman/ha-dual-smart-thermostat#138]
Hello everyone.
I can't get dual thermostat to work with a single relay.

In my case we have underfloor heating that can heat or cool.
When I use 2 different entities as heater and cooler it works perfectly, but when I try to use the same entity for cooling or heating, I only get the cooling mode, what am I doing wrong?

2 entites cooler and heater:
![Captura desde 2024-03-21 22-31-04](https://github.com/swingerman/ha-dual-smart-thermostat/assets/568784/0a58cf0d-aa99-4a31-bbb5-9ca3b05a0a0c)

![Captura desde 2024-03-21 22-32-03](https://github.com/swingerman/ha-dual-smart-thermostat/assets/568784/cb9b3bce-c52a-46a2-abc7-386aaa33f28f)

1 entitie with ac_mode set as true:

![Captura desde 2024-03-21 22-32-24](https://github.com/swingerman/ha-dual-smart-thermostat/assets/568784/74473725-936e-4a14-82da-3de37fee0ab3)

![Captura desde 2024-03-21 22-32-44](https://github.com/swingerman/ha-dual-smart-thermostat/assets/568784/f909e548-10f8-4524-9de4-729dc7e71a74)

Thank you.

**Comment by swingerman** [comment]
I did not quite get what you want to achieve.

You say heat/cool mode works perfectly.

To use the thermostat only as a heater:

```yaml
heater: switch.bw1
```

To use the thermostat only as cooler only

```yaml
heater: switch.bw2
ac_mode: true
```

Or you can use the dual mode
```yaml
heater: switch.bw1
cooler: switch.bw2
heat_cool_mode: true
```

In dual mode, you have three HVAC modes: relaxed, heat, and heat_cool. So theoretically you can set up a dual thermostat but yu can jus tue it only for heating or for cooling

**Comment by pcrednet** [comment]
Sorry for my English.

I would like to use one switch or heater and cooler, only one switch, same switch for heater and cooler, and select heat or cold Whenever you want...thx

**Comment by swingerman** [comment]
How do you switch that underfloor heating from cooling to heating with one switch? 
On -> heating
Off -> cooling?

**Comment by pcrednet** [comment]
Hello, good afternoon.
We have underfloor heating. When it is in winter mode, the thermostat opens the valve to let hot water through. When summer comes, the boiler also cools the water, so the thermostat should open when the temperature is above the set point.
That is why the same valve is used, because it is the same for everything, only that in winter it passes hot water and in summer cold water.
According to the documentation I understand that if the ac_mode attribute is set to true, the same switch is used for hot and cold, but in my case, when I activate this attribute in HA I only get the cold mode.
What am I doing wrong?

Translated with DeepL.com (free version)

**Comment by swingerman** [comment]
You will need to create two template switches from that ine switch.
Ho do your bouker know if it's in winter mode?

**Comment by pcrednet** [comment]
the boiler is integrated in the system and from its own ncontrol I tell it whether it is in winter or summer mode, that is separate.

Thank you for your answers

**Comment by swingerman** [comment]
Well, in order for the thermostat to know if it's heating or cooling at the moment, we need to let it know if the heater or cooler is on.
Because of the above problem, you need to define two switches for both heating and cooling. These can be template switches, not physical switches.
In this case, we enable the range mode so you can set minimum and maximum temperatures.

So my suggestion is to create the following:
1. add an an input boolean that you can manually set when winter mode
2. add a template switch for the heater, that combines your input boolean and your physical switch
3. add a template switch for the cooler, that combines your input boolean and your physical switch

The point is that you can manually set your system to winter/summer mode, and the two template switches will work accordingly. In winter mode, the cooler switch will always be off, and in summer mode, your heater switch will always be off.
