### ISSUE TITLE
Preset selection not removed when manually changing target temp

### ISSUE THREAD

**Issue by kdesgagnes** [swingerman/ha-dual-smart-thermostat#204]
When selecting a preset, the correct target temp is set.
When changing the target temp, the preset stays selected.
When selecting the preset again to set the target temp, nothing happens.
This started happening in version 0.95
In previous versions, when changing the target temp, the previously set preset was deselected.

**Comment by swingerman** [comment]
There was a discussion about this before that release that resulted in not dropping the current preset if you change the target temperature due to situations in which you don't intend to change the preset but intend to adjust just a little.

But if you select the preset again (from none or some other preset), the targets should be reset to what was set in the preset.
So I will look into this part as it seems to have some issues.

**Comment by kdesgagnes** [comment]
Thanks!
