### ISSUE TITLE
HVAC-MODE Fan Only?!

### ISSUE THREAD

**Issue by rrterrorr** [swingerman/ha-dual-smart-thermostat#47]
I think it's an excellent idea to have a fan-only mode.

**Comment by swingerman** [comment]
Could you elaborate on the use case, please? At this point, you can already set a fan switch as a cooler or heater.

**Comment by GloriamSemper** [comment]
@swingerman I love your work on this and it has enabled me to properly use my custom thermostat using several relays. Thank you!

I also have a need to add fan controls to your climate element. My HVAC system (as most others do in the US) have independent fan controls to cycle the house air for filtering or humidity control; without using the heating or cooling elements.

Lovelace Thermostat cards have support for controlling the fan independently from cooling or heating modes as [seen in this pic of the Simple Thermostat HACS Card](https://community-assets.home-assistant.io/original/3X/4/d/4dc02c70909ef513f03429876b29c8eae8603777.png). I believe the default lovelace thermostat even has some native fan controls.

Any chance you could get this functionality implemented into your awesome dual smart thermostat?

**Comment by swingerman** [comment]
@GloriamSemper yes. I will look into the fan controls.

**Comment by swingerman** [comment]
A separate switch will be needed for the fan. And a setting for how many degrees difference would be considered for fan mode.
Now the question arises:
Should we automatically switch between modes?
OR
It should be completely manual.
@rrterrorr 
@GloriamSemper

**Comment by rrterrorr** [comment]
Hi there,
I think it would be useful if you have the option to check at what
temperature the fan mode can be turned on... I now have it in an automatic
routine. It would be nice if this was in the Climate Control. Personally, I
would be shocked by the button alone. Better with temp control always
welcome I guess

Greetings Remo
Op wo 20 dec. 2023 11:51 schreef Miklos Szanyi ***@***.***>:

**Comment by NYZack** [comment]
Another advantage of having a fan switch is that some (most?) central AC systems require the thermostat to turn on both the AC wire ("Y" wire) and the air-handler/fan wire ("G" wire) in order to activate the AC.  Currently, I do this programmatically in Home Assistant, but it would be great if one could enable a fan-switch entity in this virtual thermostat and an option to automatically activate it whenever the cool-switch entity is activated.  Two birds with one stone (it would enable stand-alone fan capability and broaden compatibility with central AC systems).

**Comment by swingerman** [comment]
Good news. I am about to finish the fan mode feature and prepare for a beta release.
I now have a dilemma regarding `hot_tolerance`. 
How would that affect when the fan turns on?
 
Here is a use case:

current temp = 27
target temp = 24
hot_tolerance = 2
fan_hot_tolerance =1

So usually, the AC will turn on above 26 as the `hot_tolerance` is 2.
When should the fan turn on/off based on whether the temperature rises or downs?

**Comment by NYZack** [comment]
Is it clear that fan mode should be activated/deactivated by temperature at all? Don't most thermostats just allow one to turn the fan on or off (possibly simultaneously with heat and cool), possibly with a timer? 

Also, as I mentioned in my post above, I think there should be an option to activate the fan automatically with cooling, since that's how most physical thermostats work. That is, they don't just activate the Y (cooling) wire when there's a call for A/C; they activate both Y and G (fan) wires. This is unlike heating, when only the W wire is activated. HVAC systems expect this behavior.

**Comment by swingerman** [comment]
Thanks @NYZack. You will have that option but it seems that there is a need for a smart solution as well

**Comment by swingerman** [comment]
For now, I am leaning toward respecting the hot tolerance, meaning within hot_tolerance, nothing will be on. Outside hot_tolerance but within fan_hot_tolerance, we use a fan. Otherwise, we use the AC

**Comment by swingerman** [comment]
The feature is out in beta: https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.6.beta-2

**Comment by swingerman** [comment]
@NYZack 

### example
```yaml
heater: switch.study_heater
ac_mode: true
fan: switch.study_fan
fan_on_with_ac: true
```

**Comment by NYZack** [comment]
That's great. I don't know how complicated you want to make this, but some thermostats also have the option to run the fan for some time after the AC goes off, to take advantage of the coldness left in the coils after the AC turns off.  For instance, maybe fan_on_with_ac could be set to -1 if you don't want the fan to run with the A/C, and it could be set to n (a non-negative number) if you want the fan to run with the A/C and for n seconds after the A/C turns off.

**Comment by swingerman** [comment]
It seems to be a helpful feature against mould build-up.
